name: Build Godot com Bypass
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Instalar SCons
        run: pip install scons

      - name: Compilar Fase 1
        run: scons p=windows target=editor module_mono=yes mono_glue=no d3d12=no vcvars_msvc_top="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" -j 3

      - name: Gerar Glue
        shell: pwsh
        run: |
          $EXE = Get-ChildItem -Path bin/*.exe | Select-Object -First 1
          if ($EXE) {
            & $EXE.FullName --headless --generate-mono-glue modules/mono/glue
          }

      - name: Compilar Final
        run: scons p=windows target=editor module_mono=yes d3d12=no -j 3

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-com-bypass
          path: bin/
