name: Build Godot com Bypass
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Instalar SCons
        run: pip install scons

      - name: Compilar Tudo (Fluxo Unico)
        # Este comando tenta gerar o glue internamente sem precisar rodar o exe separado
        run: scons p=windows target=editor module_mono=yes d3d12=no -j 3

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-com-bypass
          path: bin/
