name: Build Godot com Bypass
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Instalar SCons
        run: pip install scons

      - name: Compilar Editor (Fase 1)
        run: scons p=windows target=editor module_mono=yes d3d12=no -j 3

      - name: Gerar Glue Codes (Bypass Máquina Cega)
        run: |
          $GODOT_EXE = Get-ChildItem -Path bin/ -Filter "*.exe" | Select-Object -First 1
          Write-Host "Iniciando Geração de Glue Force com Safe-Mode..."
          # O segredo está no --quit e no --no-window para evitar o travamento que você teve
          & $($GODOT_EXE.FullName) --headless --generate-mono-glue modules/mono/glue --quit --no-window --audio-driver Dummy

      - name: Compilar Tudo (Fase 2 - Final)
        run: scons p=windows target=editor module_mono=yes d3d12=no -j 3

      - name: Upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: godot-com-bypass-final
          path: bin/
